server:
  port: 7991
#  servlet:
#    context-path: "/seckill"


spring:
  ## 数据库设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.200:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: test
    password: 123456
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      stat-view-servlet:
        url-pattern: "/druid/*"
      filter:
        stat:
          slow-sql-millis: 2000
          log-slow-sql: true
          merge-sql: true

  ## redis
  redis:
    #数据库索引
    host: 192.168.31.200
    port: 6379
    password: 123456
    jedis:
      pool:
        #最大连接数
        max-active: 10
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 3
        #最大空闲
        max-idle: 10
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 2000

  ## thymeleaf设置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML

## mybatisplus设置
mybatis-plus:
  mapper-locations: classpath*:/mybatis/mapper/**Mapper.xml
  typeAliasesPackage: com.example.seckill.one.model.*
  global-config:
    db-config:
      id-type: auto  #主键策略自增
      db-type: mysql
      field-strategy: not_null #实体属性为null不拼入sql语句中
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #事务超时时间
    default-statement-timeout: 600
    use-generated-keys: true
    default-executor-type: reuse
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
